"""GitHub API commit and PR creation for CI/CD workflow candidates.

Creates a feature branch, commits workflow files, and opens a PR.
Never pushes directly to the base branch.
"""

from __future__ import annotations

import base64
import logging
from datetime import datetime, timezone
from typing import Any

import httpx

from orchestrator.cicd_specialist.approval import compute_candidate_hash, verify_approval
from orchestrator.cicd_specialist.models import WorkflowCandidate
from orchestrator.config import settings

logger = logging.getLogger(__name__)


class WorkflowCommitError(Exception):
    pass


async def commit_workflow_candidate(
    repo_name: str,
    candidate: WorkflowCandidate,
    approved_hash: str,
    *,
    actor: str = "automatron",
    base_branch: str = "main",
) -> dict[str, Any]:
    """Commit workflow files on a new branch and open a PR.

    Raises WorkflowCommitError if the candidate hash no longer matches the
    approved hash (mutation guard).

    Returns a dict with keys: branch, pr_url, pr_number, commit_sha.
    """
    if not verify_approval(candidate, approved_hash):
        raise WorkflowCommitError(
            "Candidate has been mutated after approval — hash mismatch; re-approval required"
        )

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    branch = f"automatron/cicd-{timestamp}"

    async with httpx.AsyncClient(
        base_url=settings.github_api_url,
        headers=_headers(),
        timeout=30,
    ) as client:
        # 1. Resolve base branch SHA
        ref_resp = await client.get(f"{_repo(repo_name)}/git/refs/heads/{base_branch}")
        ref_resp.raise_for_status()
        base_sha: str = ref_resp.json()["object"]["sha"]

        # 2. Create new branch (never touches base_branch directly)
        branch_resp = await client.post(
            f"{_repo(repo_name)}/git/refs",
            json={"ref": f"refs/heads/{branch}", "sha": base_sha},
        )
        branch_resp.raise_for_status()

        # 3. Create a blob for each workflow file
        tree_entries: list[dict[str, str]] = []
        for wf in candidate.files:
            blob_resp = await client.post(
                f"{_repo(repo_name)}/git/blobs",
                json={
                    "content": base64.b64encode(wf.content.encode("utf-8")).decode("ascii"),
                    "encoding": "base64",
                },
            )
            blob_resp.raise_for_status()
            tree_entries.append({
                "path": wf.path,
                "mode": "100644",
                "type": "blob",
                "sha": blob_resp.json()["sha"],
            })

        # 4. Get the base commit's tree SHA
        base_commit_resp = await client.get(f"{_repo(repo_name)}/git/commits/{base_sha}")
        base_commit_resp.raise_for_status()
        base_tree_sha: str = base_commit_resp.json()["tree"]["sha"]

        # 5. Create a new tree on top of the base tree
        tree_resp = await client.post(
            f"{_repo(repo_name)}/git/trees",
            json={"base_tree": base_tree_sha, "tree": tree_entries},
        )
        tree_resp.raise_for_status()
        new_tree_sha: str = tree_resp.json()["sha"]

        # 6. Create the commit
        short_hash = compute_candidate_hash(candidate)[:8]
        commit_resp = await client.post(
            f"{_repo(repo_name)}/git/commits",
            json={
                "message": (
                    f"ci: add GitHub Actions workflows (automatron/{short_hash})\n\n"
                    "Generated by Automatron CI/CD Specialist."
                ),
                "tree": new_tree_sha,
                "parents": [base_sha],
                "author": {
                    "name": settings.git_author_name,
                    "email": settings.git_author_email,
                },
            },
        )
        commit_resp.raise_for_status()
        new_commit_sha: str = commit_resp.json()["sha"]

        # 7. Advance the branch ref to the new commit
        update_resp = await client.patch(
            f"{_repo(repo_name)}/git/refs/heads/{branch}",
            json={"sha": new_commit_sha},
        )
        update_resp.raise_for_status()

        # 8. Open a PR targeting the base branch
        file_list = "\n".join(f"- `{wf.path}`" for wf in candidate.files)
        pr_resp = await client.post(
            f"{_repo(repo_name)}/pulls",
            json={
                "title": f"ci: add GitHub Actions workflows ({candidate.risk_level} risk)",
                "head": branch,
                "base": base_branch,
                "body": (
                    f"## GitHub Actions Workflows\n\n"
                    f"{candidate.summary}\n\n"
                    f"### Files\n{file_list}\n\n"
                    f"**Risk level:** {candidate.risk_level}\n\n"
                    f"Generated by Automatron CI/CD Specialist."
                ),
            },
        )
        pr_resp.raise_for_status()
        pr_data: dict[str, Any] = pr_resp.json()

        return {
            "branch": branch,
            "pr_url": pr_data["html_url"],
            "pr_number": pr_data["number"],
            "commit_sha": new_commit_sha,
        }


def _headers() -> dict[str, str]:
    if not settings.github_token:
        raise WorkflowCommitError("GITHUB_TOKEN is required for committing CI/CD workflows")
    return {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {settings.github_token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _repo(repo_name: str) -> str:
    if not settings.github_owner:
        raise WorkflowCommitError("GITHUB_OWNER is required for committing CI/CD workflows")
    return f"/repos/{settings.github_owner}/{repo_name}"
